### PR TITLE
Frame parts double buffering

### PR DESCRIPTION
**Pull request by hans1024**
Hi, I was annoyed by window title text flickering during redraws, so I added double buffering of the window frame.

### CODE REVIEW

**Comment by Nanolx** [comment]
Thanks  for sending that in.

**Comment by llaurent** [comment]
Hi there,

@hans1024 @Nanolx I'm using xinerama, I don't have double-buffer.
I'm running master with this feature reverted.
I guess it would be wiser to check for double-buffer availability instead of assuming it's there on every setup.

**Comment by Nanolx** [comment]
I'll have a look into this soon.

**Comment by Nanolx** [comment]
@llaurent could you please try again with latest git head? It should now only use DBE if it's actually available. Thanks.

**Pull request merged**
